### ISSUE TITLE
Code used for generating the relatedness_dataset

### ISSUE THREAD

**Issue by StarsLand** [dexter/dexter-datasets#1]
Dear Author @diegoceccarelli, 

The link 

git clone http://git.hpc.isti.cnr.it/ntt/dexter-relatedness.git

provided in the readme file isn't working.

Can you please, help me with this?

**Comment by diegoceccarelli** [comment]
I don't have the code anymore alas - It seems the hpc gitlab isn't running anymore - @strani might still have the code - I don't mind publishing it.

**Comment by StarsLand** [comment]
Thank you @diegoceccarelli for your prompt reply.

@strani  if you still have the code, can you please share it with me.

**Comment by strani** [comment]
Send me your email. I should have a local copy of the repo. The git server has been down for maintenance for a long time now...

**Comment by StarsLand** [comment]
@strani  here is my email address -  effattarahelal@gmail.com

**Comment by strani** [comment]
Sent by email.

**Comment by StarsLand** [comment]
Yes. I have got the mail.
Thank you so much. 

I am closing the issue.
